name: graficos_tateis
description: Um aplicativo para tornar gráficos matemáticos acessíveis para pessoas cegas.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^4.2.2
  speech_to_text: ^7.0.0
  vibration: ^3.1.0
  permission_handler: ^10.0.0
  math_expressions: ^2.3.0
  syncfusion_flutter_charts: ^28.2.3
  audioplayers: ^6.1.1
  dio: ^5.3.3
  path_provider: ^2.0.11
  path: ^1.8.3
  just_audio: ^0.9.44

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/bip.mp3