blank_issues_enabled: false
contact_links:
  - name: Documentação do Projeto
    url: https://github.com/joaopaulotest/projeto-graficos-tateis/tree/main/docs
    about: Consulte a documentação do projeto para mais informações.
